### ISSUE TITLE
V3.0.0 breaking change: Missing member SinricProContactSensor onPowerState

### ISSUE THREAD

**Issue by lilbuzz** [sinricpro/esp8266-esp32-sdk#341]
I receive the following error when I attempt to compile using v3.0.0 of the library in Arduino sketch:
Compilation error: 'using SinricProContactsensor = class SINRICPRO_3_0_0::SinricProContactsensor' {aka 'class SINRICPRO_3_0_0::SinricProContactsensor'} has no member named 'onPowerState'

**Comment by sivar2311** [comment]
Hi @lilbuzz !

The server and the app no longer support onPowerState for sensors. 
For this reason, version 3.0.0 was released, which is not backwards compatible - see [Changelog](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/changelog.md): "_BREAKING CHANGE: Remove PowerStateController from Air Quality, Contact, Motion and Temperature sensor._" and the examples for the sensors (e.g. [MotionSensor.ino](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/MotionSensor/MotionSensor.ino)).

**Comment by lilbuzz** [comment]
Thank you for this clarification.  I did look at the changelog, but it wasn't obvious to me that onPowerState was part of PowerStateController.
