### ISSUE TITLE
problems upgrading to sdk 2.9.1

### ISSUE THREAD

**Issue by sgrizzi** [sinricpro/esp8266-esp32-sdk#155]
Hi, I am having problems when upgrading my code from sdk 2.7.6 to 2.9.1.
Please also relate to issue #149 .
My code was running fine with sdk 2.7.6, which I had to continue using since the Autoconnect library -also embedded in my project- is not supporting SSL.
So I removed Autoconnect completely. Code compiles and works fine with 2.7.6.
Then I removed 2.7.6 and upgraded to 2.9.1.
I am using Platformio as the development environment.

This is the dependency graph:
Dependency Graph
|-- <ArduinoJson> 6.11.5
|-- <WebSockets> 2.3.5
|   |-- <WiFi> 1.0
|   |-- <SPI> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <ESP32 BLE Arduino> 1.0.1
|-- <Arduino_JSON> 0.1.0
|-- <TimerEvent> 0.4.2
|-- <SinricPro> 2.9.1
|   |-- <ArduinoJson> 6.11.5
|   |-- <WiFi> 1.0
|   |-- <WebSockets> 2.3.5
|   |   |-- <WiFi> 1.0
|   |   |-- <SPI> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|-- <WiFi> 1.0
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0

and this is a subset of the error listing I am getting:
In file included from .pio/libdeps/ESP32/SinricPro/src/SinricProDeviceInterface.h:5:0,
                 from .pio/libdeps/ESP32/SinricPro/src/SinricPro.h:12,
                 from src/PLH_Alexa_doorbell.cpp:12:
.pio/libdeps/ESP32/SinricPro/src/SinricProRequest.h:14:38: error: 'function' in namespace 'std' does not name a template type
 using SinricProRequestHandler = std::function<bool(SinricProRequest&)>;
                                      ^
In file included from .pio/libdeps/ESP32/SinricPro/src/SinricProTemperaturesensor.h:11:0,
                 from src/PLH_Alexa_doorbell.cpp:14:
.pio/libdeps/ESP32/SinricPro/src/SinricProDevice.h:42:15: error: 'SinricProRequestHandler' was not declared in this scope
   std::vector<SinricProRequestHandler> requestHandlers;
               ^
.pio/libdeps/ESP32/SinricPro/src/SinricProDevice.h:42:38: error: template argument 1 is invalid
   std::vector<SinricProRequestHandler> requestHandlers;
                                      ^
.pio/libdeps/ESP32/SinricPro/src/SinricProDevice.h:42:38: error: template argument 2 is invalid
In file included from .pio/libdeps/ESP32/SinricPro/src/SinricProTemperaturesensor.h:11:0,
                 from src/PLH_Alexa_doorbell.cpp:14:
.pio/libdeps/ESP32/SinricPro/src/SinricProDevice.h: In member function 'virtual bool SinricProDevice::handleRequest(SinricProRequest&)':
.pio/libdeps/ESP32/SinricPro/src/SinricProDevice.h:113:31: error: 'begin' was not declared in this scope

The platformio.ini file is identical to the one that was working fine previosusly, with the reference to the new library.

Any suggestions?
Best regards, Gabriele

**Comment by sivar2311** [comment]
Hi Gabriele!

Bug have been fixed in https://github.com/sinricpro/esp8266-esp32-sdk/commit/58ad9f286199baa1c2cafc02f2a1cb16a077be7d

**Comment by sgrizzi** [comment]
Hi Boris,
maybe a naive question.....but how do I use the fix? shall I re-download the library (it is still 2.9.1 at the moment...)? or shall I correct the file manually locally?
Rgds, Gabriele

**Comment by sgrizzi** [comment]
If I correct this "locally" it does compile fine !!!!
..but I do not know if this the most correct action to do.
Please let me know.
Rgds, Gabriele

**Comment by sivar2311** [comment]
Hi Gabriele!

This is not a naive but a completely ligitimate question :)

At the moment the fix is only in the Github repository.
I need to create a new release first to make it available through the library managers.

So at the moment there are the options
- clone / download the repository
- manually edit the local file

**Comment by sgrizzi** [comment]
Hi Boris,
well, now the code compiles correctly... but it does not run...
I get a strange sequence of messages...
Note that I did not modify my source code, and the code was running correctly - I guess that SSL is affecting the behaviour of the code.
This is ESP32 serial output:

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac



[Wifi]: Connecting....connected!
[WiFi]: IP-Address is 192.168.1.77
Timer set to 10 seconds (timerDelay variable), it will take 10 seconds before publishing the first airco reading.
Scanning BLE...
hopefully scanning in the background... [E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
abort() was called at PC 0x401b89cf on core 0

Backtrace: 0x40091f60:0x3ffe62a0 0x40092191:0x3ffe62c0 0x401b89cf:0x3ffe62e0 0x401b8a16:0x3ffe6300 0x401b8ac3:0x3ffe6320 0x401b8b46:0x3ffe6340 0x400dd882:0x3ffe6360 0x400dcbfe:0x3ffe6450 0x4014a88d:0x3ffe64a0 0x401459fe:0x3ffe64c0 0x4008e6a9:0x3ffe64f0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac



[Wifi]: Connecting....connected!
[WiFi]: IP-Address is 192.168.1.77
Timer set to 10 seconds (timerDelay variable), it will take 10 seconds before publishing the first airco reading.
Scanning BLE...
hopefully scanning in the background... [E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
....
and then it will abort and restart again...

I need your support again!
Rgds, GAbriele

**Comment by sivar2311** [comment]
Hm, this problem is not about the latest fix. 
This is about SSL / connecting issues : ESP does not connect (and crashing)

Please open new github issue for better tracking (i will close this issue now).

Meanwhile please try if this happens with #define SINRICPRO_NOSSL too

Ah... and you need the latest WebSockets library from github 
- SSL fix is not available via library managers yet (needs to be released first)
